version: "2"

services:
  server:
    build: ./server
    command: npm start
    volumes:
     - ./server:/usr/src/app
    container_name: social-trading-server
    ports:
      - "8081:8081"
    networks:
      - front-tier
      - back-tier

  redis:
    image: redis:alpine
    container_name: social-trading-redis
    ports: ["6379"]
    networks:
      - back-tier

networks:
  front-tier:
  back-tier:
